model_name: 'DQN'
model_config:
  in_channels: 4

gamma: 0.99
loss_function: smooth_l1_loss

environment:
  pixels_per_meter: 4
  darkening_factor: 0.5
  landscape_size: 128
  center_percent: 0.15
  clues: [[0.10, 0.20], [0.10, 0.20], [0.10, 0.20], 
          [0.20, 0.30], [0.20, 0.30], [0.30, 0.40], 
          [0.30, 0.40], ]
  map_seed: null
  heatmap_decay: 0.013
  terminal_time_steps: 400
  num_drones: 8
  feature_baseline: 0.5

  drone_config:
    pixel_size: 8
    mass: 2.0
    max_motor_thrust: 5.0
    time_step: 0.3

  reward_values:
    tiles: 0.2
    crash: -1.0
    clue: 3.0
    objective: 5.5
    avg: 0.2
    distance_spread: 0.2
    action_diversity: 0.3

max_power_steps: 2
len_eps: 50
episodes: 10

save_frequency: 2  # Save model every 10 episodes
reset_frequency: 5  # Reset object objetive occurs 5 times in a row