model_name: 'DQNv0'
model_config:
  in_channels: 4

gamma: 0.09
loss_function: smooth_l1_loss

environment:
  pixels_per_meter: 4
  darkening_factor: 0.5
  landscape_size: 128
  center_percent: 0.15
  clues: [[0.10, 0.20], [0.10, 0.20], [0.10, 0.20], 
          [0.20, 0.30], [0.20, 0.30], [0.30, 0.40], 
          [0.30, 0.40], ]
  map_seed: null
  heatmap_decay: 0.013
  terminal_time_steps: 400
  num_drones: 8
  feature_baseline: 0.5

  drone_config:
    pixel_size: 6
    mass: 1.5
    max_motor_thrust: 5.0
    time_step: 0.3

  reward_values:
    tiles: 0.07
    crash: -100
    clue: 0.1 
    objective: 0.4 
    avg: 0.1 
    distance_spread: 0.1 
    action_diversity: 0.1

max_power_steps: 2
len_eps: 25
episodes: 10